#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ]

rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown apache:apache "$appdir" -R

cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
mv "fetch" "fetch_$rnd.cgi"

rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown apache:apache "$contentsdir" -R
